name: JMeter Test CI/CD

on: push

jobs:
  jmeter-test:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK (since JMeter requires Java)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'  # Corrected distribution
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false

    # Install JMeter on Windows
    - name: Install JMeter
      run: |
        Invoke-WebRequest -Uri "https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz" -OutFile "apache-jmeter-5.6.3.tgz"
        tar -xvzf apache-jmeter-5.6.3.tgz
        Move-Item -Path "apache-jmeter-5.6.3" -Destination "C:\JMeter"

    # List the contents of C:\JMeter to verify extraction
    - name: Verify JMeter extraction
      run: |
        # Check if the JMeter directory exists and list the contents
        if (Test-Path "C:\JMeter\apache-jmeter-5.6.3") {
          Get-ChildItem -Path "C:\JMeter\apache-jmeter-5.6.3\bin"
        } else {
          Write-Host "JMeter directory does not exist at C:\JMeter\apache-jmeter-5.6.3"
          exit 1
        }

    # Run JMeter test plan (.jmx file) in CLI mode
    - name: Run JMeter test
      run: |
            & "C:\JMeter\apache-jmeter-5.6.3\bin\jmeter.bat" -n -t C:\Users\ribraheem\Downloads\apache-jmeter-5.6.3\apache-jmeter-5.6.3\bin\BlazedDemo -Test\HTTP Request -reserve.php .jmx -l "C:\Users\ribraheem\Downloads\apache-jmeter-5.6.3\apache-jmeter-5.6.3\bin\BlazedDemo -Test\resulr.jtl" -e -o"C:\Users\ribraheem\Downloads\apache-jmeter-5.6.3\apache-jmeter-5.6.3\bin\BlazedDemo -Test\HTML"
    # Upload the results as artifact
    - name: Upload JMeter results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: result.jtl
