name: JMeter Tests

on:
  push

jobs:
  jmeter_test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java (required for JMeter)
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
              java-version: '8'
              distribution: 'adoptium'   # Specify distribution (you can choose other distributions like 'zulu' if needed)


      # Install JMeter
      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install -y jmeter

      # Run JMeter Test
      - name: Run JMeter Test
        run: |
          jmeter -n -t "C:\Users\ribraheem\Downloads\apache-jmeter-5.6.3\apache-jmeter-5.6.3\bin\BlazedDemo -Test\HTTP Request -reserve.php .jmx" -l result.jtl
