


name: CI/CD for JMeter Tests

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK (required for JMeter)
        uses: actions/setup-java@v2
        with:
          java-version: '11' 
          distribution: 'zulu'
 # JMeter requires Java, set your version

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter Test Plan
        run: |
          jmeter -n -t ./path/to/your/test-plan.jmx -l result.jtl

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
