name: CI/CD for JMeter Tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Zulu OpenJDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # You can change the version if needed
          distribution: 'zulu'

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter Test Plan
        run: |
          jmeter -n -t ./path/to/your/test-plan.jmx -l result.jtl

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
